#!/bin/sh
#
# $FreeBSD: ports/multimedia/ffmpeg/files/ffserver.in,v 1.4 2012/01/14 08:56:07 dougb Exp $
#

# PROVIDE: ffserver
# REQUIRE: NETWORKING
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable ffserver:
#
#ffserver_enable="YES"
#
ffserver_enable="${ffserver_enable-NO}"

. /etc/rc.subr

name=ffserver
rcvar=ffserver_enable

command="/usr/local/bin/${name} &"
required_files=/usr/local/etc/ffserver.conf

load_rc_config ${name}
run_rc_command "$1"
