#! /bin/sh
#
# $FreeBSD: ports/devel/git/files/git_daemon.in,v 1.7 2012/01/14 08:55:34 dougb Exp $
#

# PROVIDE: git_daemon
# REQUIRE: DAEMON
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable git_daemon:
#
#git_daemon_enable="YES"

. /etc/rc.subr

name="git_daemon"
rcvar=git_daemon_enable

load_rc_config $name

: ${git_daemon_enable:=NO}
: ${git_daemon_directory:=/usr/local/git}
: ${git_daemon_flags:="--syslog --reuseaddr --detach"}

command="/usr/local/libexec/git-core/git-daemon"
command_args="${git_daemon_directory}"

PATH="${PATH}:/usr/local/libexec/git-core"

run_rc_command "$1"
