#!/bin/sh
#
# $FreeBSD: ports/comms/lirc/files/lircd.in,v 1.1 2012/08/05 23:19:36 dougb Exp $
#
# PROVIDE: lircd
# REQUIRE: DAEMON
#
# Add the following line to /etc/rc.conf to enable lircd:
#
# lircd_enable="YES"
#

. /etc/rc.subr

name="lircd"
rcvar=lircd_enable

load_rc_config ${name}
: ${lircd_enable="NO"}
: ${lircd_device="/dev/lirc0"}

procname=/usr/local/sbin/lircd
pidfile=/var/run/lirc/lircd.pid
lircd_config="/usr/local/etc/lircd.conf"
required_files=${lircd_config}
command="/usr/local/sbin/lircd"
command_args="-d ${lircd_device} ${lircd_config}"

run_rc_command "$1"
