#!/bin/sh
#
# $FreeBSD: ports/net/mDNSResponder/files/mdnsd.in,v 1.2 2012/01/14 08:56:18 dougb Exp $

# PROVIDE: mdnsd
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name=mdnsd
rcvar=mdnsd_enable

load_rc_config $name

: ${mdnsd_enable="NO"}
: ${mdnsd_pidfile="/var/run/${name}.pid"}

command="/usr/local/sbin/${name}"
pidfile="${mdnsd_pidfile}"

run_rc_command $*
